import meetliImage from './assets/image_for_meetli.png';
import djImage from './assets/dj_feuerwerk.PNG';

export type Language = 'de' | 'en' | 'uk';

export const languageOptions: Array<{ code: Language; label: string; name: string }> = [
  { code: 'de', label: 'DE', name: 'Deutsch' },
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'uk', label: 'UA', name: 'Українська' },
];

const portfolioLinks = {
  wedding: {
    image: 'https://raw.githubusercontent.com/schob-digital/Hochzeitsservicede/main/src/Foto/boat.png',
    link: 'https://schob-digital.github.io/Hochzeitsservicede/',
  },
  dj: {
    image: djImage,
    link: 'https://vasilygenai.github.io/DJ_Vasily/',
  },
  misjudged: {
    image: 'https://raw.githubusercontent.com/VasilyGenAI/Website_me/main/Photos/Screen2.png',
    link: 'https://vasilygenai.github.io/misjudged.app/index.html',
  },
  schob: {
    image: 'https://raw.githubusercontent.com/VasilyGenAI/Website_me/main/Photos/first_image.png',
    link: 'https://vasilygenai.github.io/Website_me/',
    contain: true,
  },
  meetli: {
    image: meetliImage,
    link: 'https://www.meetli.ch/',
  },
};

export const siteContent = {
  de: {
    metaTitle: 'Schob Digital | Websites in einem Tag',
    nav: {
      portfolio: 'Referenzen',
      difference: 'Unterschied',
      calendly: 'Erstgespräch',
      packages: 'Leistungen',
      contact: 'Kontakt',
      imprint: 'Impressum',
      privacy: 'Datenschutz',
    },
    hero: {
      intro: 'Hey, ich bin Vasily.',
      headlineStart: 'Ich baue dir in nur einem Tag eine',
      highlighted: 'Website',
      headlineEnd: 'die Besucher in Kunden verwandelt.',
      subline: 'Kostenfreie Erstberatung online',
      cta: 'Gespräch buchen',
      imageAlt: 'Vasily Schob von Schob Digital',
    },
    portfolio: {
      eyebrow: 'Referenzen',
      items: [
        {
          ...portfolioLinks.wedding,
          title: 'Hochzeitsservice',
          desc: 'Elegantes Design für Hochzeitsfotografie und mehr.',
        },
        {
          ...portfolioLinks.dj,
          title: 'DJ Vasily',
          desc: 'Professioneller Auftritt für DJ & Event-Equipment.',
        },
        {
          ...portfolioLinks.misjudged,
          title: 'Misjudged Web',
          desc: 'Kompakte Website zur App. Fokus auf sauberen Datenschutz.',
        },
        {
          ...portfolioLinks.schob,
          title: 'Diese Website',
          desc: 'Fokus auf Marketing, Struktur und Designqualität.',
        },
        {
          ...portfolioLinks.meetli,
          title: 'Meetli',
          desc: 'Universitäts-Projekt mit Fokus auf saubere Nutzerführung.',
        },
      ],
    },
    difference: {
      eyebrow: 'Unterschied zu der Konkurrenz',
      titleLine1: 'Ihr Erfolg,',
      titleLine2: 'ohne Friktion.',
      intro: 'Sie haben Besseres zu tun, als auf eine Website zu warten. Entdecken Sie den Unterschied.',
      items: [
        {
          title: 'Schnelligkeit',
          desc: 'Sie bekommen Ihre Website nicht erst in zwei Wochen, sondern innerhalb eines Tages. Durch eine clevere Kombination aus standardisierten Prozessen und Ihren persönlichen Design-Präferenzen entsteht die Website enorm schnell.',
        },
        {
          title: 'Vertrauen',
          desc: 'Sie haben die Möglichkeit auf ein persönliches 1:1-Gespräch vor Ort in Berlin oder auf einen flexiblen Online-Termin. So können wir uns besser kennenlernen und schauen, ob eine Zusammenarbeit passt. Alles völlig unverbindlich.',
        },
        {
          title: 'Konzern-Qualität zum Start-up-Preis',
          desc: 'Ich bringe die Professionalität und Datensicherheit aus meiner Zeit bei Accenture und der ETH Zürich mit - aber zu Preisen, die sich auch kleine Unternehmen leisten können.',
        },
        {
          title: 'Unternehmerisches Denken',
          desc: 'Ich bin selbst Unternehmer und nicht nur IT-Consultant. Ich kenne Themen wie Kostenminimierung, Effizienz und Eigenverantwortung aus erster Hand. Bei mir gibt es kein "Dafür bin ich nicht zuständig, das macht mein Kollege" - ich bin Ihr direkter Ansprechpartner.',
        },
        {
          title: 'Kostentransparenz',
          desc: 'Ein fester Preis. Keine versteckten Gebühren, keine bösen Überraschungen am Ende des Monats.',
        },
      ],
    },
    calendly: {
      eyebrow: 'Erstgespräch',
      title: 'Lass uns sprechen.',
      desc: 'Wir können unverbindlich 30 Minuten über die Website sprechen und schauen, ob eine Zusammenarbeit passt. Such dir einfach einen Termin aus.',
    },
    packages: {
      eyebrow: 'Leistungen',
      badge: 'Unser Bestseller',
      request: 'Anfragen',
      plusVat: 'zzgl. MwSt.',
      items: [
        {
          id: 'starter',
          name: 'Paket 1',
          title: 'Starter',
          subtitle: 'Der Conversion-Boost',
          price: '299',
          intro: 'Perfekt für den schnellen und effektiven Markteintritt.',
          highlight: false,
          features: [
            'Hochkonvertierende One-Page-Landingpage: Ein messerscharfes Design, das deine Besucher gezielt durch dein Angebot führt und direkt zu Kunden macht.',
            'Responsives Design: Sieht auf Smartphone, Tablet und Desktop perfekt aus.',
            'Rasante Ladezeiten: Keine abgesprungenen Kunden durch langsames Laden.',
          ],
        },
        {
          id: 'professional',
          name: 'Paket 2',
          title: 'Professional',
          subtitle: 'Sicher & Sorglos',
          price: '499',
          intro: 'Unser Bestseller. Dein professioneller Auftritt ohne rechtliche Kopfschmerzen.',
          highlight: true,
          features: [
            'Alles aus dem Starter-Paket (One-Page-Landingpage).',
            'Rechtssicherheit inklusive: Einbindung von Impressum und Datenschutzerklärung nach aktuellen Vorgaben.',
            'Fokus auf dein Business: Du kümmerst dich um deine Kunden, wir um das rechtliche Fundament deiner Website.',
          ],
        },
        {
          id: 'premium',
          name: 'Paket 3',
          title: 'Premium',
          subtitle: 'Datenbasiertes Wachstum',
          price: '799',
          intro: 'Für Unternehmer, die nichts dem Zufall überlassen wollen.',
          highlight: false,
          features: [
            'Alles aus dem Professional-Paket (Landingpage + Rechtstexte).',
            'Profi-Web-Analytics: Vollständige Einrichtung von Tracking-Tools.',
            'Besucher verstehen: Miss genau, woher deine Kunden kommen, was sie klicken und wie du deinen Umsatz weiter maximieren kannst.',
          ],
        },
      ],
    },
    support: {
      title: 'Optionale Add-ons: Monatliche Betreuung',
      cancel: 'Jederzeit kündbar',
      intro: 'Lass uns die Technik übernehmen, damit du dich aufs Geschäft konzentrieren kannst.',
      period: '/ Monat',
      options: [
        {
          id: 'basic',
          title: 'Basic Support',
          price: '20',
          lead: 'Deine Website bleibt lebendig und aktuell.',
          desc: 'Beinhaltet 1 Anpassung oder Feature-Anfrage pro Monat (z.B. Texte aktualisieren, Bilder tauschen, kleine Layout-Korrekturen).',
        },
        {
          id: 'premium',
          title: 'Premium Support',
          price: '50',
          lead: 'Dein technischer Partner für kontinuierliches Wachstum.',
          desc: 'Umfassende Betreuung für dein skalierendes Business. Beinhaltet auch komplexe Änderungen und die Entwicklung komplett neuer Unterseiten, wenn dein Angebot wächst.',
        },
      ],
      none: 'Kein Support Add-on',
    },
    contact: {
      eyebrow: 'Projekt anfragen',
      title: 'Lass uns starten.',
      successTitle: 'Danke für deine Anfrage!',
      successText: 'Ich melde mich so schnell wie möglich bei dir.',
      newRequest: 'Neue Anfrage',
      subject: 'Neue Website-Anfrage über Schob Digital',
      name: 'Name',
      email: 'E-Mail',
      company: 'Unternehmen',
      service: 'Service-Paket',
      servicePlaceholder: 'Bitte auswählen',
      customService: 'Individuell',
      support: 'Optionales Support Add-on',
      message: 'Welche Art von Website brauchst du gerade konkret?',
      consentStart: 'Ich stimme zu, dass meine Angaben zur Bearbeitung meiner Anfrage verarbeitet werden. Weitere Informationen stehen in der',
      consentLink: 'Datenschutzerklärung',
      consentEnd: '.',
      submit: 'Projekt anfragen',
    },
    footer: {
      rights: 'Alle Rechte vorbehalten.',
      cookieSettings: 'Cookie-Einstellungen',
    },
  },
  en: {
    metaTitle: 'Schob Digital | Websites in one day',
    nav: {
      portfolio: 'Work',
      difference: 'Difference',
      calendly: 'Consultation',
      packages: 'Services',
      contact: 'Contact',
      imprint: 'Legal Notice',
      privacy: 'Privacy',
    },
    hero: {
      intro: "Hey, I'm Vasily.",
      headlineStart: 'I build you a',
      highlighted: 'website',
      headlineEnd: 'in just one day that turns visitors into customers.',
      subline: 'Free online consultation',
      cta: 'Book a call',
      imageAlt: 'Vasily Schob from Schob Digital',
    },
    portfolio: {
      eyebrow: 'Selected work',
      items: [
        {
          ...portfolioLinks.wedding,
          title: 'Wedding Service',
          desc: 'Elegant design for wedding photography and related services.',
        },
        {
          ...portfolioLinks.dj,
          title: 'DJ Vasily',
          desc: 'A professional web presence for DJ and event equipment.',
        },
        {
          ...portfolioLinks.misjudged,
          title: 'Misjudged Web',
          desc: 'Compact app website with a clear privacy focus.',
        },
        {
          ...portfolioLinks.schob,
          title: 'This Website',
          desc: 'Focused on marketing, structure, and design quality.',
        },
        {
          ...portfolioLinks.meetli,
          title: 'Meetli',
          desc: 'University project focused on clear user guidance.',
        },
      ],
    },
    difference: {
      eyebrow: 'What makes it different',
      titleLine1: 'Your success,',
      titleLine2: 'without friction.',
      intro: 'You have better things to do than wait for a website. Discover the difference.',
      items: [
        {
          title: 'Speed',
          desc: 'You do not get your website in two weeks, but within one day. A smart combination of standardized processes and your personal design preferences makes the build extremely fast.',
        },
        {
          title: 'Trust',
          desc: 'You can choose a personal 1:1 meeting in Berlin or a flexible online appointment. That gives us a chance to get to know each other and see whether working together makes sense, with no obligation.',
        },
        {
          title: 'Enterprise quality at a start-up price',
          desc: 'I bring the professionalism and data-security mindset from my time at Accenture and ETH Zurich, but at prices that are realistic for small businesses.',
        },
        {
          title: 'Entrepreneurial thinking',
          desc: 'I am an entrepreneur myself, not only an IT consultant. I know cost control, efficiency, and ownership first-hand. With me, you have one direct contact.',
        },
        {
          title: 'Transparent pricing',
          desc: 'One fixed price. No hidden fees and no unpleasant surprises at the end of the month.',
        },
      ],
    },
    calendly: {
      eyebrow: 'Consultation',
      title: "Let's talk.",
      desc: 'We can talk about your website for 30 minutes with no obligation and see whether working together is a fit. Just choose a time that works for you.',
    },
    packages: {
      eyebrow: 'Services',
      badge: 'Best seller',
      request: 'Request',
      plusVat: 'plus VAT',
      items: [
        {
          id: 'starter',
          name: 'Package 1',
          title: 'Starter',
          subtitle: 'The conversion boost',
          price: '299',
          intro: 'Perfect for a fast and effective market entry.',
          highlight: false,
          features: [
            'High-converting one-page landing page: a focused design that guides visitors through your offer and turns them into customers.',
            'Responsive design: polished on smartphone, tablet, and desktop.',
            'Fast load times: no lost customers because the website feels slow.',
          ],
        },
        {
          id: 'professional',
          name: 'Package 2',
          title: 'Professional',
          subtitle: 'Secure & worry-free',
          price: '499',
          intro: 'The best seller. A professional web presence without legal headaches.',
          highlight: true,
          features: [
            'Everything from the Starter package (one-page landing page).',
            'Legal foundation included: integration of legal notice and privacy policy based on current requirements.',
            'Focus on your business: you take care of your customers, I take care of the legal foundation of your website.',
          ],
        },
        {
          id: 'premium',
          name: 'Package 3',
          title: 'Premium',
          subtitle: 'Data-driven growth',
          price: '799',
          intro: 'For entrepreneurs who do not want to leave growth to chance.',
          highlight: false,
          features: [
            'Everything from the Professional package (landing page plus legal texts).',
            'Professional web analytics: full setup of tracking tools.',
            'Understand visitors: measure where customers come from, what they click, and how you can keep increasing revenue.',
          ],
        },
      ],
    },
    support: {
      title: 'Optional add-ons: monthly support',
      cancel: 'Cancel anytime',
      intro: 'Let me handle the technical side so you can focus on your business.',
      period: '/ month',
      options: [
        {
          id: 'basic',
          title: 'Basic Support',
          price: '20',
          lead: 'Your website stays alive and up to date.',
          desc: 'Includes 1 adjustment or feature request per month, such as updating text, replacing images, or small layout fixes.',
        },
        {
          id: 'premium',
          title: 'Premium Support',
          price: '50',
          lead: 'Your technical partner for continuous growth.',
          desc: 'Comprehensive support for a scaling business. Also includes more complex changes and entirely new subpages as your offer grows.',
        },
      ],
      none: 'No support add-on',
    },
    contact: {
      eyebrow: 'Request a project',
      title: "Let's get started.",
      successTitle: 'Thanks for your request!',
      successText: 'I will get back to you as soon as possible.',
      newRequest: 'New request',
      subject: 'New website request via Schob Digital',
      name: 'Name',
      email: 'Email',
      company: 'Company',
      service: 'Service package',
      servicePlaceholder: 'Please choose',
      customService: 'Custom',
      support: 'Optional support add-on',
      message: 'What kind of website do you need right now?',
      consentStart: 'I agree that my information may be processed to handle my request. More information is available in the',
      consentLink: 'privacy policy',
      consentEnd: '.',
      submit: 'Request project',
    },
    footer: {
      rights: 'All rights reserved.',
      cookieSettings: 'Cookie settings',
    },
  },
  uk: {
    metaTitle: 'Schob Digital | Сайти за один день',
    nav: {
      portfolio: 'Портфоліо',
      difference: 'Переваги',
      calendly: 'Зустріч',
      packages: 'Послуги',
      contact: 'Контакт',
      imprint: 'Вихідні дані',
      privacy: 'Приватність',
    },
    hero: {
      intro: 'Привіт, я Василь.',
      headlineStart: 'Я створю для вас',
      highlighted: 'сайт',
      headlineEnd: 'всього за один день, який перетворює відвідувачів на клієнтів.',
      subline: 'Безкоштовна онлайн-консультація',
      cta: 'Записатися',
      imageAlt: 'Василь Шоб зі Schob Digital',
    },
    portfolio: {
      eyebrow: 'Портфоліо',
      items: [
        {
          ...portfolioLinks.wedding,
          title: 'Весільний сервіс',
          desc: 'Елегантний дизайн для весільної фотографії та суміжних послуг.',
        },
        {
          ...portfolioLinks.dj,
          title: 'DJ Vasily',
          desc: 'Професійна онлайн-презентація для DJ та event-обладнання.',
        },
        {
          ...portfolioLinks.misjudged,
          title: 'Misjudged Web',
          desc: 'Компактний сайт застосунку з чітким фокусом на приватність.',
        },
        {
          ...portfolioLinks.schob,
          title: 'Цей сайт',
          desc: 'Фокус на маркетингу, структурі та якості дизайну.',
        },
        {
          ...portfolioLinks.meetli,
          title: 'Meetli',
          desc: 'Університетський проєкт із фокусом на зрозумілий шлях користувача.',
        },
      ],
    },
    difference: {
      eyebrow: 'Чим я відрізняюся',
      titleLine1: 'Ваш успіх,',
      titleLine2: 'без зайвих перешкод.',
      intro: 'У вас є важливіші справи, ніж чекати на сайт тижнями. Ось у чому різниця.',
      items: [
        {
          title: 'Швидкість',
          desc: 'Ви отримуєте сайт не через два тижні, а протягом одного дня. Завдяки продуманим процесам і вашим дизайн-побажанням сайт створюється дуже швидко.',
        },
        {
          title: 'Довіра',
          desc: 'Можна домовитися про особисту 1:1 зустріч у Берліні або обрати гнучкий онлайн-термін. Так ми спокійно познайомимося і зрозуміємо, чи підходить співпраця.',
        },
        {
          title: 'Корпоративна якість за ціною старту',
          desc: 'Я приношу професійність і увагу до безпеки даних з досвіду в Accenture та ETH Zurich, але за цінами, доступними для малого бізнесу.',
        },
        {
          title: 'Підприємницьке мислення',
          desc: 'Я сам підприємець, а не лише IT-консультант. Тому добре розумію витрати, ефективність і відповідальність. Ви працюєте напряму зі мною.',
        },
        {
          title: 'Прозора вартість',
          desc: 'Одна фіксована ціна. Без прихованих платежів і неприємних сюрпризів наприкінці місяця.',
        },
      ],
    },
    calendly: {
      eyebrow: 'Перша розмова',
      title: 'Поговорімо.',
      desc: 'Ми можемо без зобов’язань 30 хвилин поговорити про ваш сайт і зрозуміти, чи підходить співпраця. Просто оберіть зручний час.',
    },
    packages: {
      eyebrow: 'Послуги',
      badge: 'Найпопулярніше',
      request: 'Запит',
      plusVat: '+ ПДВ',
      items: [
        {
          id: 'starter',
          name: 'Пакет 1',
          title: 'Starter',
          subtitle: 'Буст конверсії',
          price: '299',
          intro: 'Ідеально для швидкого й ефективного старту.',
          highlight: false,
          features: [
            'Landing page з високою конверсією: чіткий дизайн, який веде відвідувачів через вашу пропозицію і перетворює їх на клієнтів.',
            'Адаптивний дизайн: якісно виглядає на смартфоні, планшеті та desktop.',
            'Швидке завантаження: менше втрачених клієнтів через повільний сайт.',
          ],
        },
        {
          id: 'professional',
          name: 'Пакет 2',
          title: 'Professional',
          subtitle: 'Безпечно і спокійно',
          price: '499',
          intro: 'Найпопулярніший варіант. Професійна присутність онлайн без зайвого юридичного головного болю.',
          highlight: true,
          features: [
            'Усе з пакета Starter (one-page landing page).',
            'Юридична основа включена: інтеграція Impressum та політики конфіденційності за актуальними вимогами.',
            'Фокус на бізнесі: ви займаєтеся клієнтами, я беру на себе технічну та юридичну основу сайту.',
          ],
        },
        {
          id: 'premium',
          name: 'Пакет 3',
          title: 'Premium',
          subtitle: 'Зростання на основі даних',
          price: '799',
          intro: 'Для підприємців, які не хочуть залишати зростання випадковості.',
          highlight: false,
          features: [
            'Усе з пакета Professional (landing page + юридичні тексти).',
            'Професійна вебаналітика: повне налаштування tracking-інструментів.',
            'Розуміння відвідувачів: вимірюйте, звідки приходять клієнти, що вони натискають і як збільшувати дохід.',
          ],
        },
      ],
    },
    support: {
      title: 'Додатково: щомісячна підтримка',
      cancel: 'Можна скасувати будь-коли',
      intro: 'Я беру технічну частину на себе, щоб ви могли зосередитися на бізнесі.',
      period: '/ місяць',
      options: [
        {
          id: 'basic',
          title: 'Basic Support',
          price: '20',
          lead: 'Ваш сайт залишається живим і актуальним.',
          desc: 'Включає 1 правку або feature-запит на місяць, наприклад оновлення текстів, заміну зображень або невеликі layout-корекції.',
        },
        {
          id: 'premium',
          title: 'Premium Support',
          price: '50',
          lead: 'Ваш технічний партнер для постійного зростання.',
          desc: 'Комплексна підтримка для бізнесу, що масштабується. Також включає складніші зміни та створення нових підсторінок, коли ваша пропозиція зростає.',
        },
      ],
      none: 'Без support add-on',
    },
    contact: {
      eyebrow: 'Запит на проєкт',
      title: 'Почнімо.',
      successTitle: 'Дякую за ваш запит!',
      successText: 'Я відповім вам якнайшвидше.',
      newRequest: 'Новий запит',
      subject: 'Новий запит на сайт через Schob Digital',
      name: 'Ім’я',
      email: 'Email',
      company: 'Компанія',
      service: 'Пакет послуг',
      servicePlaceholder: 'Оберіть варіант',
      customService: 'Індивідуально',
      support: 'Додаткова підтримка',
      message: 'Який сайт вам потрібен саме зараз?',
      consentStart: 'Я погоджуюся, що мої дані можуть оброблятися для відповіді на мій запит. Більше інформації міститься в',
      consentLink: 'політиці конфіденційності',
      consentEnd: '.',
      submit: 'Надіслати запит',
    },
    footer: {
      rights: 'Усі права захищено.',
      cookieSettings: 'Налаштування cookie',
    },
  },
} as const;
